apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-bus
  name: test-filter-env-app-bus
  namespace: openshift-gitops
spec:
  destination:
    namespace: test-filter-env
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/test-filter-env/apps/app-bus/overlays
    repoURL: https://github.com/ciiay/gitops.git
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
