apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-train
  name: test-refresh-env-app-train
  namespace: openshift-gitops
spec:
  destination:
    namespace: test-refresh-env
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/test-refresh-env/apps/app-train/overlays
    repoURL: https://github.com/ciiay/gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
